# Generated by Django 3.1.2 on 2022-07-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publishedAt',
            field=models.DateField(),
        ),
    ]
