# Generated by Django 3.1.2 on 2022-07-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20220702_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, upload_to='file'),
        ),
    ]
