# Generated by Django 3.1.2 on 2022-07-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_book_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='./media')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
