# Generated by Django 3.1.2 on 2022-07-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20220703_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='user',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
