# Generated by Django 3.1.2 on 2022-07-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20220703_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='dateuploaded',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
