# Generated by Django 3.1.2 on 2022-07-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_fileupload_dateuploaded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='dateuploaded',
            new_name='date_uploaded',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='file_type',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
