# Generated by Django 3.1.2 on 2022-07-03 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0007_auto_20220703_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='user_id',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
